baseURL = 'https://shokoohi.cf/'

defaultContentLanguage = "en"
theme = "coder"

[languages]
  [languages.en]
    languageName = "English"
    languageCode = "en-us"
    title = "Ali Shokoohi Website"

  [languages.fa]
    languageName = "فارسی"
    languageCode = "ir-fa"
    languagedirection = "rtl"
    rtl = true
    title = "وبسایت علی شکوهی"
