baseURL = 'https://shokoohi.cf/'

defaultContentLanguage = 'en"

[languages]
  [languages.en]
    languageName = "English"
    languageCode = "en-us"
    title = "Ali Shokoohi Website"

  [languages.fa]
    languageName = ":fa:"
    languageCode = "ir-fa"
    languagedirection = "rtl"
    rtl = true
    title = "وبسایت علی شکوهی"
