baseURL = 'https://ali-shokoohi.github.io/'

defaultContentLanguage = "en"
theme = "coder"

[languages]
  [languages.en]
    languageName = "English"
    languageCode = "en-us"
    title = "Ali Shokoohi Website"
  [languages.en.params]
    author = "Ali Shokoohi"
    info = "Back-End Developer"
    description = "Ali Shokoohi's personal website"
    footercontent = "Publish is allowed only as free"
  [languages.en.taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"
    author = "authors"
  [[languages.en.menu.main]]
    name = "About"
    weight = 1
    url = "about/"


  [languages.fa]
    languageName = "فارسی"
    languageCode = "ir-fa"
    languagedirection = "rtl"
    rtl = true
    title = "وبسایت علی شکوهی"
  [languages.fa.params]
    author = "علی شکوهی"
    info = "توسعه دهنده ی وب"
    description = "وب سایت شخصی علی شکوهی"
    footercontent = "انتشار فقط به صورت رایگان مجاز است"
  [languages.fa.taxonomies]
    category = "دسته بندی ها"
    series = "سری ها"
    tag = "تگ ها"
    author = "نویسنده ها"
  [[languages.fa.menu.main]]
    name = "درباره"
    weight = 1
    url = "about/"

[params]
keywords = "blog,developer,personal"

avatarurl = '/img/avatar.jpg'
favicon_32 = "/img/favicon-32x32.ico"
favicon_16 = "/img/favicon-16x16.ico"

hideFooter = false
hideCredits = false
hideCopyright = false
since = 2021

enableTwemoji = true

colorScheme = "auto"
hidecolorschemetoggle = false

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/ali-shokoohi/"
[[params.social]]
  name = "Gitlab"
  icon = "fa fa-gitlab fa-2x"
  weight = 2
  url = "https://gitlab.com/shokoohi/"
[[params.social]]
  name = "Twitter"
  icon = "fa fa-twitter fa-2x"
  weight = 3
  url = "https://twitter.com/MrShokoohi/"

